spring.application.name=customer-api

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/customer_api_db
spring.datasource.username=postgres
spring.datasource.password=theplanetisflat

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#my login credentials
spring.security.user.name =thato
spring.security.password =password123 


#JWT Configuration
jwt.secret=MyBankSuperSecretKeyThatIsAtLeast256BitsLongForSecurity
#this is the secret key used to sign toens


jwt.expiration=86400000
#86400000 = 24 hours
#after 24 hours the token will expire


server.port=8081
