package com.banking.banking_api.dto;

import com.banking.banking_api.model.AccountType;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class AccountRequestDTO {

    @NotNull(message = "Account type is required")
    private AccountType accountType;
    // customer chooses: SAVINGS, CURRENT, or BUSINESS
    // this is the only field customer sends
    // everything else is generated by the system
}